Update to Fedora 35
keylime/keylime-vagrant-ansible-tpm-emulator pull request #56
Opened 2022-03-25 14:57 UTC by axelsimon

Align on installer.sh:
- update packages task
- stop using abrmd

Note: creates a working Keylime VM, but exporting the following
environment variable is still needed to start keylime_agent:
export TPM2TOOLS_TCTI="mssim:port=2321"

2022-03-27 00:52 UTC, axelsimon commented
@mpeters Something for you when you have a moment. Unless @lukehinds wants to sign-off on this one :)

2022-03-29 13:53 UTC, mpeters requested changes
Very nice! I was just commenting to someone the other day that we needed to do this. Some questions and small suggested changes

2022-03-29 13:53 UTC, mpeters commented on Vagrantfile
>        keylime.vm.network "forwarded_port", guest: 443, host: "844#{i}"
The forwarded ports are a great idea to make the test env more useful when you have other machines to connect. Thanks for that

2022-03-31 13:03 UTC, mpeters approved these changes

2022-03-31 13:03 UTC, merged